/* 
 * Author:  Jacob Autrey
 * Course:  COMP-003A-L01
 * Purpose: Code fpr Assignment 1
 */
namespace COMP003A.Assignment1
{
    internal class Program
    {
        static void Main(string[] args) 
        {
            System.Console.WriteLine("100 Things About Me");
            System.Console.WriteLine("1.");
            System.Console.WriteLine("2.");
            System.Console.WriteLine("3.");
            System.Console.WriteLine("4.");
            System.Console.WriteLine("5.");
            System.Console.WriteLine("6.");
            System.Console.WriteLine("7.");
            System.Console.WriteLine("8.");
            System.Console.WriteLine("9.");
            System.Console.WriteLine("10.");
            System.Console.WriteLine("11.");
            System.Console.WriteLine("12.");
            System.Console.WriteLine("13.");
            System.Console.WriteLine("14.");
            System.Console.WriteLine("15.");
            System.Console.WriteLine("16.");
            System.Console.WriteLine("17.");
            System.Console.WriteLine("18.");
            System.Console.WriteLine("19.");
            System.Console.WriteLine("20.");
            System.Console.WriteLine("21.");
            System.Console.WriteLine("22.");
            System.Console.WriteLine("23.");
            System.Console.WriteLine("24.");
            System.Console.WriteLine("25.");
            System.Console.WriteLine("26.");
            System.Console.WriteLine("27.");
            System.Console.WriteLine("28.");
            System.Console.WriteLine("29.");
            System.Console.WriteLine("30");
            System.Console.WriteLine("31.");
            System.Console.WriteLine("32.");
            System.Console.WriteLine("33.");
            System.Console.WriteLine("34.");
            System.Console.WriteLine("35.");
            System.Console.WriteLine("36.");
            System.Console.WriteLine("37.");
            System.Console.WriteLine("38.");
            System.Console.WriteLine("39.");
            System.Console.WriteLine("40.");
            System.Console.WriteLine("41.");
            System.Console.WriteLine("42.");
            System.Console.WriteLine("43.");
            System.Console.WriteLine("44.");
            System.Console.WriteLine("45.");
            System.Console.WriteLine("46.");
            System.Console.WriteLine("47.");
            System.Console.WriteLine("48.");
            System.Console.WriteLine("49.");
            System.Console.WriteLine("50.");
            System.Console.WriteLine("51.");
            System.Console.WriteLine("52.");
            System.Console.WriteLine("53.");
            System.Console.WriteLine("54.");
            System.Console.WriteLine("55.");
            System.Console.WriteLine("56.");
            System.Console.WriteLine("57.");
            System.Console.WriteLine("58.");
            System.Console.WriteLine("59.");
            System.Console.WriteLine("60.");
            System.Console.WriteLine("61.");
            System.Console.WriteLine("62.");
            System.Console.WriteLine("63.");
            System.Console.WriteLine("64.");
            System.Console.WriteLine("65.");
            System.Console.WriteLine("66.");
            System.Console.WriteLine("67.");
            System.Console.WriteLine("68.");
            System.Console.WriteLine("69.");
            System.Console.WriteLine("70.");
            System.Console.WriteLine("71.");
            System.Console.WriteLine("72.");
            System.Console.WriteLine("73.");
            System.Console.WriteLine("74.");
            System.Console.WriteLine("75.");
            System.Console.WriteLine("76.");
            System.Console.WriteLine("77.");
            System.Console.WriteLine("78.");
            System.Console.WriteLine("79.");
            System.Console.WriteLine("80.");
            System.Console.WriteLine("81.");
            System.Console.WriteLine("82.");
            System.Console.WriteLine("83.");
            System.Console.WriteLine("84.");
            System.Console.WriteLine("85.");
            System.Console.WriteLine("86.");
            System.Console.WriteLine("87.");
            System.Console.WriteLine("88.");
            System.Console.WriteLine("89.");
            System.Console.WriteLine("90.");
            System.Console.WriteLine("91.");
            System.Console.WriteLine("92.");
            System.Console.WriteLine("93.");
            System.Console.WriteLine("94.");
            System.Console.WriteLine("95.");
            System.Console.WriteLine("96.");
            System.Console.WriteLine("97.");
            System.Console.WriteLine("98.");
            System.Console.WriteLine("99.");
            System.Console.WriteLine("100.");
        }
    }
}
